name: Selenium Tests with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven Tests
        run: mvn clean test

      - name: Install Allure
        run: |
          sudo apt-add-repository ppa:qameta/allure
          sudo apt-get update
          sudo apt-get install allure

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report